---
- name: install requirements
  hosts: raspi
  remote_user: pi
  become: true
  vars:
    sysctl_config:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1

  tasks:
    - name: update cache
      apt:
        update_cache: yes
    - name: install required packages
      apt:
        state: latest
        pkg:
          - hostapd
          - dnsmasq
          - netfilter-persistent
          - iptables-persistent
          - radvd

    # Set ip forwarding on in /proc and in the sysctl file and reload if necessary
    - name: enable ip forwarding
      sysctl:
        name: '{{ item.key }}'
        value: '{{ item.value }}'
        sysctl_set: yes
        state: present
      with_dict: '{{ sysctl_config }}'
