- hosts: raspi
  remote_user: pi
  become: true
  roles:
  - radius
  - ap
  tasks:
    - name: setup chillispot
      include_role:
        name: chilli
      tags:
        - hotspot
    
    - name: configure monitoring
      include_role:
        name: custom
      tags:
        - custom
