- name: restart radvd
  systemd:
    name: radvd
    state: restarted

- name: restart network
  service:
    name: networking
    state: restarted

- name: restart hostapd
  systemd:
    name: hostapd
    state: restarted

- name: restart dnsmasq
  systemd:
    name: dnsmasq
    state: restarted

- name: save iptables
  command: netfilter-persistent save
