- name: restart radvd
  systemd:
    name: radvd
    state: restarted

- name: restart hostapd
  systemd:
    name: hostapd
    state: restarted

- name: restart dnsmasq
  systemd:
    name: dnsmasq
    state: restarted

- name: generate resolv
  command: resolvconf -u

- name: restart freeradius
  systemd:
    name: freeradius
    state: restarted

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: restart network
  service:
    name: systemd-networkd
    state: restarted

- name: save iptables
  command: netfilter-persistent save
