---
- name: remove nginx default website
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
  tags:
    - hotspot

- name: configure nginx for captive portal
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/chilli.conf
  tags:
    - hotspot

- name: enable chilli page on nginx
  file:
    src: ../sites-available/chilli.conf
    dest: /etc/nginx/sites-enabled/chilli.conf
    state: link
  notify: restart nginx
  tags:
    - hotspot


- name: ensure /var/www/chilli is present
  file:
    path: /var/www/chilli
    state: directory
  tags:
    - hotspot

- name: configure web page
  template:
    src: hotspotlogin.php.j2
    dest: /var/www/chilli/hotspotlogin.php
  tags:
    - hotspot

- name: configure chilli
  template:
    src: chilli.j2
    dest: /etc/chilli/config
  notify: restart chilli
  tags:
    - hotspot

- name: enable chilli
  systemd:
    name: chilli
    state: started
    enabled: yes
  tags:
    - hotspot

- name: configure disconnect handler
  template:
    src: chilli_disconnect.sh.j2
    dest: /chilli_disconnect.sh
    mode: '0755'
  tags:
    - hotspot

- name: create disconnect handler service
  copy:
    src: chilli_disconnect.service
    dest: /etc/systemd/system/chilli_disconnect.service
    mode: '0700'
  tags:
    - hotspot

- name: enable disconnect handler
  systemd:
    name: chilli_disconnect
    state: started
    enabled: yes
  tags:
    - hotspot