---
- name: configure hostapd
  template:
    src: hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf
  notify: restart hostapd
  tags:
    - ap

- name: configure interfaces
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  notify: restart network
  with_items:
    - { src: 'templates/networkd/lan.network.j2', dest: '/etc/systemd/network/lan.network' }
    - { src: 'templates/networkd/eap.network.j2', dest: '/etc/systemd/network/eap.network' }
    - { src: 'templates/networkd/cwp.network.j2', dest: '/etc/systemd/network/cwp.network' }
  tags:
    - network

- name: configure resolv.conf to use dnsmasq
  template:
    src: resolvconf.conf.j2
    dest: /etc/resolvconf.conf
  notify: generate resolv
  tags:
    - dnsmasq
  
- name: configure dnsmasq
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/wlan.conf
  tags:
    - dnsmasq

- name: configure radvd
  template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf
  notify: restart radvd
  tags:
    - radvd

- name: configure freeradius
  template:
    src: radius/default.j2
    dest: /etc/freeradius/3.0/sites-available/default
  notify: restart freeradius
  tags:
    - radius

- name: configure freeradius inner-tunnel
  template:
    src: radius/inner-tunnel.j2
    dest: /etc/freeradius/3.0/sites-available/inner-tunnel
  notify: restart freeradius
  tags:
    - radius

- name: configure freeradius users
  template:
    src: radius/users.j2
    dest: /etc/freeradius/3.0/mods-config/files/authorize
  notify: restart freeradius
  tags:
    - radius

- name: copy test certificates
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'files/ca.pem', dest: '/etc/freeradius/3.0/certs/ca.pem' }
    - { src: 'files/server.pem', dest: '/etc/freeradius/3.0/certs/server.pem' }
  notify: restart freeradius
  tags:
    - radius

- name: configure freeradius eap
  template:
    src: radius/eap.j2
    dest: /etc/freeradius/3.0/mods-available/eap
  notify: restart freeradius
  tags:
    - radius

- name: remove nginx default website
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
  tags:
    - hotspot

- name: configure nginx for captive portal
  template:
    src: hotspot/nginx.conf.j2
    dest: /etc/nginx/conf.d/hotspot.conf
  notify: restart nginx
  tags:
    - hotspot

- name: configure web page
  template:
    src: hotspot/hotspotlogin.php.j2
    dest: /var/www/hotspot/hotspotlogin.php
  tags:
    - hotspot

- name: ensure chilli is started
  lineinfile:
    path: /etc/default/chilli
    regexp: '^START_CHILLI='
    line: START_CHILLI=1
  tags:
    - hotspot

- name: configure chilli
  template:
    src: hotspot/chilli.j2
    dest: /etc/chilli/config
  notify: restart chilli
  tags:
    - hotspot

- name: enable NAT for IPv4
  iptables:
    ip_version: ipv4
    table: nat
    chain: POSTROUTING
    out_interface: eth0
    jump: MASQUERADE
  notify:
    - save iptables
    #  - restart hostapd
  tags:
    - nat

- name: enable NAT for IPv6
  iptables:
    ip_version: ipv6
    table: nat
    chain: POSTROUTING
    out_interface: eth0
    jump: MASQUERADE
  notify:
    - save iptables
    #- restart hostapd
  tags:
    - nat